spring.application.name=myallpet


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-mute-feather-a242vhhe-pooler.eu-central-1.aws.neon.tech:5432/AllMyPet?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WL4D8wAZNqkP
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=voBeR1CW5JRivJirqNC3akixDBHEzgnEDiSO5HMxAfY=
jwt.expiration-ms=604800000

spring.jpa.show-sql=true
 
server.port=5555

# logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG

# In application.properties
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace


logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type=TRACE 


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
